version: '3.8'

services:
  # 1. База данных
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    healthcheck: # Добавляем проверку готовности базы
      test: ["CMD-SHELL", "pg_isready -U user -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    # Прописываем всё прямо в команду без лишних переменных
    command: 
      - -path=/migrations/ 
      - -database=postgres://user:password@postgres:5432/wallet_db?sslmode=disable 
      - up
    depends_on:
      postgres:
        condition: service_healthy


  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
 