version: '3.8'

services:
  # 1. База данных
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    healthcheck: # Добавляем проверку готовности базы
      test: ["CMD-SHELL", "pg_isready -U user -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    # Прописываем всё прямо в команду без лишних переменных
    command: 
      - -path=/migrations/ 
      - -database=postgres://user:password@postgres:5432/wallet_db?sslmode=disable 
      - up
    depends_on:
      postgres:
        condition: service_healthy



  # 3. Приложение с Air
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DB_SOURCE=postgres://user:password@postgres:5432/wallet_db?sslmode=disable
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
